### ISSUE TITLE
Unable to run "Usage" example from README.md

### ISSUE THREAD

**Issue by tancredosouza** [turingpointde/cvss.js#28]
# Steps Taken

- Created a new directory called test: `mkdir test && cd test`
- Installed lib with `yarn`: `yarn add @turingpointde/cvss.js`
- Copied and pasted the "Usage" example to a local `index.js` file
- Ran `node index.js`

# Expected Result
```
5.5
4.7
Medium - Based on Qualitative Severity Rating Scale
CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:L/E:U/RL:T/RC:R
{ CVSS: "3.0", AV: "N", AC: "H", PR: "L", UI: "R", S: "C", C: "L", I: "L", A: "L", E: "U", RL: "T", RC: "R" }
```

# Actual Result
```
5.5
/Users/tantan/workspace/hacktoberfest/test/index.js:6
console.log(vector.getTemporalScore()); // 4.7
                   ^

TypeError: vector.getTemporalScore is not a function
    at Object.<anonymous> (/Users/tantan/workspace/hacktoberfest/test/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by Fubinator** [comment]
This ist because I did not publish the newest version on npm. I'm going to do that tomorrow. Good Catch @tancredosouza

**Comment by Fubinator** [comment]
Should be up to date now @tancredosouza

**Comment by tancredosouza** [comment]
Thanks for looking into this!
